# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name
title: "Window Retrofit Resources for Historic Property Owners" 
# Website URL
baseURL: 'https://historicwindow.netlify.app/' 
canonifyURLs: true




###########################################
## Set site‑wide defaults the layouts read 
###########################################
# I want to hide all dates on default, and turn them on manually using front matters
params:
  features:
    page:
      date: false      # hide the published date under the title by default
      lastmod: false   # hide the “Last updated” line by default
  descriptions: "Research-based practical window retrofit resources for historic building owners"
  umami_analytics:
    enabled: true
    src: "https://cloud.umami.is/script.js"
    website_id: "6a7e9ec8-ec89-4902-8eb1-5820f1aa8017"
    domains: "historicwindow.netlify.app"
    environments: ["production"]
# Add a global cascade that hides all date variants (covers different layouts that use different flags)
cascade:
  # Global default for all content
  - _target:
      path: /**        # applies to everything under content/
    show_date: false
    show_lastmod: false         # used by many “page” layouts
    show_date_updated: false    # used by some “docs” layouts

# Add module to run umami-analytics
module:
  imports:
    path: github.com/hugomods/umami-analytics

############################
## PAGE OPTIONS
############################

# cascade:
#   # Docs folder options
#   - _target:
#       path: /docs/**
#     editable: true
#     show_breadcrumb: true
#     # Hide date from Next In Series
#     show_date: true
#     # Show date modified at end of content
#     show_date_updated: false
#   # Blog post options
#   - _target:
#       path: /updates/**
#       kind: page
#     pager: true
#     editable: true
#     hide_date: false
#     show_date_updated: true
#     reading_time: true
#     commentable: false
#     show_related: true
#     share: true
#     # Just use Breadcrumb for navigation on blog post pages?
#     show_breadcrumb: false
#     header:
#       navbar:
#         enable: true

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
enableInlineShortcodes: true
disableAliases: true
outputs:
  home: [HTML, SITEMAP, ROBOTS, RSS, WebAppManifest, headers, redirects, backlinks]
  page: [HTML]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
  # below ensure HTML will show up
  goldmark:
    renderer:
      unsafe: true
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep
