# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: blue

# SEO
marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'Window Retrofit Resources for Historic Property Owners'
    description: 'A retrofit resource site for historic property owners in Edinburgh and wider Scotland, focusing on windows.'
    twitter: ''
  analytics:
    google_analytics: ''
    google_tag_manager: ''
    microsoft_clarity: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "Test"
      # Logo filename in `assets/media/` folder
      filename: "uoelogo2.svg"
    # button:
    #   enable: true
    #   text: "Get Started"
    #   url: "https://hugoblox.com/templates/details/docs/"
    show_search: true
    show_theme_chooser: true

search: # this only works on actual site, not in preview (hugo server)
  enable: true
  suggestions: []
  quick_actions: []

# Site footer
footer:
  copyright:
    notice: 'Â© {year} W. Victoria Lee. This work is licensed under {license} unless otherwise noted.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false


# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: true


